/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Metodos.Correo;
import Metodos.Destino;
import Metodos.Guadar;
import Metodos.Paquete;
import Metodos.Pago;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Cajas extends javax.swing.JFrame {
       String gmail = "";
       String name = "";
       
    /**
     * Creates new form Cajas
     */
    public Cajas() {
        initComponents();
        this.setLocationRelativeTo(null);
        Productos producto = new Productos();
        gmail = producto.correo;
        sesion Sesion = new sesion();
        name = Sesion.nombre;
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCajas = new javax.swing.JLabel();
        jLabelTamaño = new javax.swing.JLabel();
        jComboBoxTamaño = new javax.swing.JComboBox();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabelPeso = new javax.swing.JLabel();
        jTextFielPeso = new javax.swing.JTextField();
        jLabelDestino = new javax.swing.JLabel();
        jLabelPais = new javax.swing.JLabel();
        jTextFieldPais = new javax.swing.JTextField();
        jLabelciudad = new javax.swing.JLabel();
        jLabeldireccion = new javax.swing.JLabel();
        jTextFielddirecion = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jLabelkg = new javax.swing.JLabel();
        jTextFieldciudad = new javax.swing.JTextField();
        jLabelTotalPagar = new javax.swing.JLabel();
        jButtonTotalPagar = new javax.swing.JButton();
        jLabelfondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCajas.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelCajas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCajas.setText("CAJAS");
        getContentPane().add(jLabelCajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 120, 30));

        jLabelTamaño.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTamaño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTamaño.setText("Tamaño");
        getContentPane().add(jLabelTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 110, 30));

        jComboBoxTamaño.setBackground(new java.awt.Color(153, 255, 153));
        jComboBoxTamaño.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxTamaño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Seleccionar-", "Grande", "Pequeño" }));
        jComboBoxTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTamañoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 120, 30));

        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCantidad.setText("Cantidad:");
        getContentPane().add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 20));

        jTextFieldCantidad.setBackground(new java.awt.Color(153, 255, 153));
        jTextFieldCantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 190, 30));

        jLabelPeso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPeso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPeso.setText("Peso:");
        getContentPane().add(jLabelPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, 20));

        jTextFielPeso.setBackground(new java.awt.Color(153, 255, 153));
        jTextFielPeso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFielPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFielPesoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFielPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, 30));

        jLabelDestino.setBackground(new java.awt.Color(153, 255, 153));
        jLabelDestino.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelDestino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDestino.setText("DESTINO");
        getContentPane().add(jLabelDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 100, 30));

        jLabelPais.setBackground(new java.awt.Color(153, 255, 153));
        jLabelPais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPais.setText("Pais:");
        getContentPane().add(jLabelPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 20));

        jTextFieldPais.setBackground(new java.awt.Color(153, 255, 153));
        jTextFieldPais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPaisKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 190, -1));

        jLabelciudad.setBackground(new java.awt.Color(153, 255, 153));
        jLabelciudad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelciudad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelciudad.setText("Ciudad:");
        getContentPane().add(jLabelciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, 20));

        jLabeldireccion.setBackground(new java.awt.Color(153, 255, 143));
        jLabeldireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabeldireccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeldireccion.setText("Direccion:");
        getContentPane().add(jLabeldireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, 30));

        jTextFielddirecion.setBackground(new java.awt.Color(153, 255, 153));
        jTextFielddirecion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFielddirecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 190, -1));

        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 100, 30));

        jLabelkg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelkg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelkg.setText("Kg");
        getContentPane().add(jLabelkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 40, 30));

        jTextFieldciudad.setBackground(new java.awt.Color(153, 255, 153));
        jTextFieldciudad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldciudadKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 190, -1));

        jLabelTotalPagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTotalPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 190, 30));

        jButtonTotalPagar.setText("Aceptar");
        jButtonTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalPagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 100, 30));

        jLabelfondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caja.jpg"))); // NOI18N
        getContentPane().add(jLabelfondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTamañoActionPerformed
        Guadar guardar = new Guadar();
        Paquete obj1 = new Paquete();
        Destino des1 = new Destino();
        Pago pago1 = new Pago();
    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        // TODO add your handling code here:
        
        
        obj1.setTamaño(this.jComboBoxTamaño.getSelectedItem().toString());
        obj1.setCantidad(this.jTextFieldCantidad.getText());
        obj1.setPeso(this.jTextFielPeso.getText());
        
        
        des1.setPais(this.jTextFieldPais.getText());
        des1.setDireccion(this.jTextFielddirecion.getText());
        des1.setCiudad(this.jTextFieldciudad.getText());
        
        
        
        if(this.jComboBoxTamaño.getSelectedItem().equals("-Seleccionar-")|| this.jTextFielPeso.getText().isEmpty() || this.jTextFieldCantidad.getText().isEmpty() || this.jTextFieldPais.getText().isEmpty()||this.jTextFieldciudad.getText().isEmpty()||this.jTextFielddirecion.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"Debe rellenar todos los campos");
        }else{
            
        guardar.guardarDatosPaquete(obj1.getTamaño(),obj1.getCantidad(),obj1.getPeso());
        guardar.guardarDestino(des1.getPais(),des1.getDireccion(),des1.getCiudad());
        Correo correo = new Correo();
        correo.Correo(gmail,mensaje());
        JOptionPane.showMessageDialog(null,"Datos guardado con exito");
        }
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jButtonTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalPagarActionPerformed
        // TODO add your handling code here:
        if(this.jComboBoxTamaño.getSelectedItem().equals("-Seleccionar-")|| this.jTextFielPeso.getText().isEmpty() || this.jTextFieldCantidad.getText().isEmpty() || this.jTextFieldPais.getText().isEmpty()||this.jTextFieldciudad.getText().isEmpty()||this.jTextFielddirecion.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"Debe rellenar todos los campos");
        }else{
        this.jLabelTotalPagar.setText(pago1.Pago(this.jTextFieldCantidad.getText(),this.jTextFielPeso.getText()));
        this.setVisible(true);
        }
    }//GEN-LAST:event_jButtonTotalPagarActionPerformed

    private void jTextFieldCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(Character.isDigit(caracter)){
          evt.consume();
        }  
    }//GEN-LAST:event_jTextFieldCantidadKeyTyped

    private void jTextFielPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFielPesoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(Character.isDigit(caracter)){
          evt.consume();
        }  
    }//GEN-LAST:event_jTextFielPesoKeyTyped

    private void jTextFieldPaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPaisKeyTyped
        // TODO add your handling code here:
        int caracter = evt.getKeyChar();
        if(Character.isDigit(caracter)){
          evt.consume();
        }  
    }//GEN-LAST:event_jTextFieldPaisKeyTyped

    private void jTextFieldciudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldciudadKeyTyped
        // TODO add your handling code here:
        int caracter = evt.getKeyChar();
        if(Character.isDigit(caracter)){
          evt.consume();
        }  
    }//GEN-LAST:event_jTextFieldciudadKeyTyped

    public String mensaje(){
        return "Señor(a) "+name +" usted ha realizado un envio de Cajas la cual su Destino es "+des1.getPais()
                +" la ciudad es " +des1.getCiudad() +" y su direccion es " +des1.getDireccion() +"." +this.jLabelTotalPagar.getText();
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cajas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonTotalPagar;
    private javax.swing.JComboBox jComboBoxTamaño;
    private javax.swing.JLabel jLabelCajas;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelTamaño;
    private javax.swing.JLabel jLabelTotalPagar;
    private javax.swing.JLabel jLabelciudad;
    private javax.swing.JLabel jLabeldireccion;
    private javax.swing.JLabel jLabelfondo3;
    private javax.swing.JLabel jLabelkg;
    private javax.swing.JTextField jTextFielPeso;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldciudad;
    private javax.swing.JTextField jTextFielddirecion;
    // End of variables declaration//GEN-END:variables
}
