/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import Metodos.CedulaValidacion;
import Metodos.Cliente;
import Metodos.Guadar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class Productos extends javax.swing.JFrame {
          
           String nombre = "";
           
          
           
    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        sesion Sesion = new sesion();
        nombre = Sesion.nombre;
       
    }
     public static String correo ="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelcedula = new javax.swing.JLabel();
        jTextFieldcedula = new javax.swing.JTextField();
        jLabelcorreo = new javax.swing.JLabel();
        jLabelEnvios = new javax.swing.JLabel();
        jComboBoxProductos = new javax.swing.JComboBox();
        jButtonIngresarEnvios = new javax.swing.JButton();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelLogo = new javax.swing.JLabel();
        jLabelfondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelcedula.setBackground(new java.awt.Color(0, 255, 102));
        jLabelcedula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelcedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelcedula.setText("Cedula:");
        getContentPane().add(jLabelcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 80, 20));

        jTextFieldcedula.setBackground(new java.awt.Color(102, 153, 255));
        jTextFieldcedula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldcedulaKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 160, -1));

        jLabelcorreo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelcorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelcorreo.setText("Correo:");
        getContentPane().add(jLabelcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 90, 20));

        jLabelEnvios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEnvios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEnvios.setText("ENVIOS DISPONIBLES");
        getContentPane().add(jLabelEnvios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 170, 40));

        jComboBoxProductos.setBackground(new java.awt.Color(102, 153, 255));
        jComboBoxProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxProductos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Seleccionar-", "Cajas", "Documentos", "Vestimenta" }));
        jComboBoxProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 130, 30));

        jButtonIngresarEnvios.setBackground(new java.awt.Color(0, 51, 102));
        jButtonIngresarEnvios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonIngresarEnvios.setText("Ingresar");
        jButtonIngresarEnvios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarEnviosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresarEnvios, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 110, 30));

        jTextFieldCorreo.setBackground(new java.awt.Color(102, 153, 255));
        jTextFieldCorreo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 160, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabelfondo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelfondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/waallpapers.jpg"))); // NOI18N
        getContentPane().add(jLabelfondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarEnviosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarEnviosActionPerformed
        // TODO add your handling code here:
        
       correo = this.jTextFieldCorreo.getText();
       
       Cliente obj1 = new Cliente();
       obj1.setNombre(nombre);
       obj1.setCedula(this.jTextFieldcedula.getText());
       obj1.setGmail(this.jTextFieldCorreo.getText());
        
       Guadar guardar = new Guadar(); 
       CedulaValidacion obj = new CedulaValidacion();
       if(!obj.cerificarCedula(this.jTextFieldcedula.getText()) || !this.esEmailValido(this.jTextFieldCorreo.getText())){
         JOptionPane.showMessageDialog(null,"Ingrese una cedula valida o correo valido");
       } 
       else{
           guardar.guardardatos(obj1.getNombre(),obj1.getCedula(),obj1.getGmail());
           JOptionPane.showMessageDialog(null,"datos guardados en exito");
                 
           if((this.jComboBoxProductos.getSelectedItem().equals("Cajas"))){  
           Cajas cajas = new Cajas();
           cajas.setVisible(true);
           this.dispose();
           }
           if((this.jComboBoxProductos.getSelectedItem().equals("Vestimenta"))){
           Vestimenta vestimenta = new Vestimenta();
           vestimenta.setVisible(true);
           this.dispose();
           }
           if((this.jComboBoxProductos.getSelectedItem().equals("Documentos"))){
            Documentos documentos = new Documentos();
            documentos.setVisible(true);
            this.dispose();
           }
           
       }
        
       
    }//GEN-LAST:event_jButtonIngresarEnviosActionPerformed
     
    private void jTextFieldcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldcedulaKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(!Character.isDigit(caracter)){
          evt.consume();
        }
    }//GEN-LAST:event_jTextFieldcedulaKeyTyped

    private void jComboBoxProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProductosActionPerformed

     public boolean esEmailValido(String correo){
        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^(.+)@(.+)$");
        mat = pat.matcher(correo);
        return (mat.find());
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresarEnvios;
    private javax.swing.JComboBox jComboBoxProductos;
    private javax.swing.JLabel jLabelEnvios;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelcedula;
    private javax.swing.JLabel jLabelcorreo;
    private javax.swing.JLabel jLabelfondo2;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldcedula;
    // End of variables declaration//GEN-END:variables
}
