/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Metodos.Cliente;
import Metodos.Correo;
import Metodos.Destino;
import Metodos.Guadar;
import Metodos.Pago;
import Metodos.Paquete;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Vestimenta extends javax.swing.JFrame {
         String gmail = "";
         String name = "";
    /**
     * Creates new form Vestimenta
     */
    public Vestimenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        Productos producto = new Productos();
        gmail = producto.correo;
        sesion Sesion = new sesion();
        name = Sesion.nombre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelVestimenta = new javax.swing.JLabel();
        jLabelTamaño = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCantidadV = new javax.swing.JTextField();
        jLabelPesoV = new javax.swing.JLabel();
        jTextFieldPesoV = new javax.swing.JTextField();
        jLabelDestinoV = new javax.swing.JLabel();
        jLabelPaisV = new javax.swing.JLabel();
        jTextFieldPaisV = new javax.swing.JTextField();
        jLabelCiudadV = new javax.swing.JLabel();
        jTextFieldDireccionV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCiudad = new javax.swing.JTextField();
        jButtonEnviarV = new javax.swing.JButton();
        jComboBoxTamaño = new javax.swing.JComboBox();
        jButtonAceptar = new javax.swing.JButton();
        jLabelTotalPagar = new javax.swing.JLabel();
        jLabelPeso = new javax.swing.JLabel();
        jLabelfondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelVestimenta.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelVestimenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVestimenta.setText("VESTIMENTA");
        getContentPane().add(jLabelVestimenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 110, 40));

        jLabelTamaño.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTamaño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTamaño.setText("Tamaño");
        getContentPane().add(jLabelTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 80, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cantidad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 80, 20));

        jTextFieldCantidadV.setBackground(new java.awt.Color(153, 255, 153));
        jTextFieldCantidadV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadVKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldCantidadV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 170, -1));

        jLabelPesoV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPesoV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPesoV.setText("Peso");
        getContentPane().add(jLabelPesoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 60, -1));

        jTextFieldPesoV.setBackground(new java.awt.Color(153, 255, 153));
        jTextFieldPesoV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPesoV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPesoVKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldPesoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 170, -1));

        jLabelDestinoV.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelDestinoV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDestinoV.setText("DESTINO");
        getContentPane().add(jLabelDestinoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 140, 30));

        jLabelPaisV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPaisV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPaisV.setText("Pais");
        getContentPane().add(jLabelPaisV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 20));

        jTextFieldPaisV.setBackground(new java.awt.Color(153, 255, 153));
        jTextFieldPaisV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPaisV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPaisVKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldPaisV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 180, -1));

        jLabelCiudadV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCiudadV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCiudadV.setText("Direccion");
        getContentPane().add(jLabelCiudadV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 60, 20));

        jTextFieldDireccionV.setBackground(new java.awt.Color(153, 255, 153));
        jTextFieldDireccionV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldDireccionV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 180, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ciudad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 60, -1));

        jTextFieldCiudad.setBackground(new java.awt.Color(153, 255, 153));
        jTextFieldCiudad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCiudadActionPerformed(evt);
            }
        });
        jTextFieldCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCiudadKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 180, -1));

        jButtonEnviarV.setBackground(new java.awt.Color(155, 250, 155));
        jButtonEnviarV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEnviarV.setText("Enviar");
        jButtonEnviarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarVActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 193, 100, 30));

        jComboBoxTamaño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Selecionar-", "Grande", "Pequeño" }));
        getContentPane().add(jComboBoxTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 120, 30));

        jButtonAceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 100, 30));

        jLabelTotalPagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTotalPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 170, 30));

        jLabelPeso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPeso.setText("Kg");
        getContentPane().add(jLabelPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, 20));

        jLabelfondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ropa.png"))); // NOI18N
        getContentPane().add(jLabelfondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        Guadar guardar = new Guadar();
        Paquete obj1 = new Paquete();
        Destino destino = new Destino();
        Pago pago1 = new Pago();
   
        
    private void jButtonEnviarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarVActionPerformed
        // TODO add your handling code here:
        Guadar guardar = new Guadar();
        Paquete obj1 = new Paquete();
        
        obj1.setCantidad(this.jTextFieldCantidadV.getText());
        obj1.setPeso(this.jTextFieldPesoV.getText());
        obj1.setTamaño(this.jComboBoxTamaño.getSelectedItem().toString());
        
        
        destino.setPais(this.jTextFieldPaisV.getText());
        destino.setCiudad(this.jTextFieldCiudad.getText());
        destino.setDireccion(this.jTextFieldDireccionV.getText());
        
        if(this.jComboBoxTamaño.getSelectedItem().equals("-Seleccionar-")|| this.jTextFieldPesoV.getText().isEmpty() || this.jTextFieldCantidadV.getText().isEmpty() || this.jTextFieldPaisV.getText().isEmpty()|| this.jTextFieldPaisV.getText().isEmpty() || this.jTextFieldDireccionV.getText().isEmpty()||this.jTextFieldCiudad.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"Debe rellenar todos los campos");
        }else{
          guardar.guardarDatosPaquete(obj1.getTamaño(),obj1.getCantidad(), obj1.getPeso());
          guardar.guardarDestino(destino.getPais(),destino.getCiudad(), destino.getDireccion());
          Correo correo = new Correo();
          correo.Correo(gmail,mensaje());
          JOptionPane.showMessageDialog(null,"Datos guardado con exito");
        }
        
    }//GEN-LAST:event_jButtonEnviarVActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        if(this.jComboBoxTamaño.getSelectedItem().equals("-Seleccionar-")|| this.jTextFieldPesoV.getText().isEmpty() || this.jTextFieldCantidadV.getText().isEmpty() || this.jTextFieldPaisV.getText().isEmpty()||jTextFieldCiudad.getText().isEmpty()||jTextFieldDireccionV.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"Debe rellenar todos los campos");
        }else{
        this.jLabelTotalPagar.setText(pago1.Pago(this.jTextFieldCantidadV.getText(),this.jTextFieldPesoV.getText()));
        this.jLabelTotalPagar.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTextFieldCantidadVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadVKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(!Character.isDigit(caracter)){
          evt.consume();
        }  
    }//GEN-LAST:event_jTextFieldCantidadVKeyTyped

    private void jTextFieldPesoVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesoVKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(!Character.isDigit(caracter)){
          evt.consume();
        }  
    }//GEN-LAST:event_jTextFieldPesoVKeyTyped

    private void jTextFieldPaisVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPaisVKeyTyped
        // TODO add your handling code here:
        int caracter = evt.getKeyChar();
        if(Character.isDigit(caracter)){
          evt.consume();
        }  
    }//GEN-LAST:event_jTextFieldPaisVKeyTyped

    private void jTextFieldCiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCiudadKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(Character.isDigit(caracter)){
          evt.consume();
        }  
    }//GEN-LAST:event_jTextFieldCiudadKeyTyped

    private void jTextFieldCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCiudadActionPerformed
        
     public String mensaje(){
        return "Señor(a) "+name +" usted ha realizado un envio de Vestimenta la cual su Destino es "+destino.getPais()
                +" la ciudad es " +destino.getCiudad() +" y su direccion es " +destino.getDireccion() +" " +this.jLabelTotalPagar.getText();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vestimenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vestimenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vestimenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vestimenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vestimenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonEnviarV;
    private javax.swing.JComboBox jComboBoxTamaño;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCiudadV;
    private javax.swing.JLabel jLabelDestinoV;
    private javax.swing.JLabel jLabelPaisV;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelPesoV;
    private javax.swing.JLabel jLabelTamaño;
    private javax.swing.JLabel jLabelTotalPagar;
    private javax.swing.JLabel jLabelVestimenta;
    private javax.swing.JLabel jLabelfondo3;
    private javax.swing.JTextField jTextFieldCantidadV;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldDireccionV;
    private javax.swing.JTextField jTextFieldPaisV;
    private javax.swing.JTextField jTextFieldPesoV;
    // End of variables declaration//GEN-END:variables
}
